export interface Item {
  code: string;
  name: string;
  type: 'country' | 'state';
  continent?: string;
}

export const ITEMS: Item[] = [
  // Países
  { code: 'br', name: 'Brasil', type: 'country', continent: 'América do Sul' },
  { code: 'us', name: 'Estados Unidos', type: 'country', continent: 'América do Norte' },
  { code: 'ar', name: 'Argentina', type: 'country', continent: 'América do Sul' },
  { code: 'fr', name: 'França', type: 'country', continent: 'Europa' },
  { code: 'de', name: 'Alemanha', type: 'country', continent: 'Europa' },
  { code: 'it', name: 'Itália', type: 'country', continent: 'Europa' },
  { code: 'es', name: 'Espanha', type: 'country', continent: 'Europa' },
  { code: 'pt', name: 'Portugal', type: 'country', continent: 'Europa' },
  { code: 'gb', name: 'Reino Unido', type: 'country', continent: 'Europa' },
  { code: 'jp', name: 'Japão', type: 'country', continent: 'Ásia' },
  { code: 'cn', name: 'China', type: 'country', continent: 'Ásia' },
  { code: 'ru', name: 'Rússia', type: 'country', continent: 'Europa/Ásia' },
  { code: 'ca', name: 'Canadá', type: 'country', continent: 'América do Norte' },
  { code: 'au', name: 'Austrália', type: 'country', continent: 'Oceania' },
  { code: 'mx', name: 'México', type: 'country', continent: 'América do Norte' },
  { code: 'cl', name: 'Chile', type: 'country', continent: 'América do Sul' },
  { code: 'uy', name: 'Uruguai', type: 'country', continent: 'América do Sul' },
  { code: 'py', name: 'Paraguai', type: 'country', continent: 'América do Sul' },
  { code: 'co', name: 'Colômbia', type: 'country', continent: 'América do Sul' },
  { code: 'pe', name: 'Peru', type: 'country', continent: 'América do Sul' },
  { code: 'za', name: 'África do Sul', type: 'country', continent: 'África' },
  { code: 'eg', name: 'Egito', type: 'country', continent: 'África' },
  { code: 'ng', name: 'Nigéria', type: 'country', continent: 'África' },
  { code: 'kr', name: 'Coreia do Sul', type: 'country', continent: 'Ásia' },
  { code: 'in', name: 'Índia', type: 'country', continent: 'Ásia' },
  { code: 'gr', name: 'Grécia', type: 'country', continent: 'Europa' },
  { code: 'tr', name: 'Turquia', type: 'country', continent: 'Europa/Ásia' },
  { code: 'nl', name: 'Holanda', type: 'country', continent: 'Europa' },
  { code: 'be', name: 'Bélgica', type: 'country', continent: 'Europa' },
  { code: 'ch', name: 'Suíça', type: 'country', continent: 'Europa' },
  { code: 'se', name: 'Suécia', type: 'country', continent: 'Europa' },
  { code: 'no', name: 'Noruega', type: 'country', continent: 'Europa' },
  { code: 'dk', name: 'Dinamarca', type: 'country', continent: 'Europa' },
  { code: 'fi', name: 'Finlândia', type: 'country', continent: 'Europa' },
  { code: 'ie', name: 'Irlanda', type: 'country', continent: 'Europa' },
  { code: 'at', name: 'Áustria', type: 'country', continent: 'Europa' },
  { code: 'pl', name: 'Polônia', type: 'country', continent: 'Europa' },
  { code: 'il', name: 'Israel', type: 'country', continent: 'Ásia' },
  { code: 'sa', name: 'Arábia Saudita', type: 'country', continent: 'Ásia' },
  { code: 'ae', name: 'Emirados Árabes', type: 'country', continent: 'Ásia' },
  { code: 'th', name: 'Tailândia', type: 'country', continent: 'Ásia' },
  { code: 'vn', name: 'Vietnã', type: 'country', continent: 'Ásia' },
  { code: 'id', name: 'Indonésia', type: 'country', continent: 'Ásia' },
  { code: 'nz', name: 'Nova Zelândia', type: 'country', continent: 'Oceania' },
  { code: 'cu', name: 'Cuba', type: 'country', continent: 'América Central' },
  { code: 'jm', name: 'Jamaica', type: 'country', continent: 'América Central' },
  { code: 'pa', name: 'Panamá', type: 'country', continent: 'América Central' },
  { code: 'cr', name: 'Costa Rica', type: 'country', continent: 'América Central' },

  // Estados Brasileiros (flagcdn usa br-xx)
  { code: 'br-ac', name: 'Acre', type: 'state' },
  { code: 'br-al', name: 'Alagoas', type: 'state' },
  { code: 'br-am', name: 'Amazonas', type: 'state' },
  { code: 'br-ap', name: 'Amapá', type: 'state' },
  { code: 'br-ba', name: 'Bahia', type: 'state' },
  { code: 'br-ce', name: 'Ceará', type: 'state' },
  { code: 'br-df', name: 'Distrito Federal', type: 'state' },
  { code: 'br-es', name: 'Espírito Santo', type: 'state' },
  { code: 'br-go', name: 'Goiás', type: 'state' },
  { code: 'br-ma', name: 'Maranhão', type: 'state' },
  { code: 'br-mg', name: 'Minas Gerais', type: 'state' },
  { code: 'br-ms', name: 'Mato Grosso do Sul', type: 'state' },
  { code: 'br-mt', name: 'Mato Grosso', type: 'state' },
  { code: 'br-pa', name: 'Pará', type: 'state' },
  { code: 'br-pb', name: 'Paraíba', type: 'state' },
  { code: 'br-pe', name: 'Pernambuco', type: 'state' },
  { code: 'br-pi', name: 'Piauí', type: 'state' },
  { code: 'br-pr', name: 'Paraná', type: 'state' },
  { code: 'br-rj', name: 'Rio de Janeiro', type: 'state' },
  { code: 'br-rn', name: 'Rio Grande do Norte', type: 'state' },
  { code: 'br-ro', name: 'Rondônia', type: 'state' },
  { code: 'br-rr', name: 'Roraima', type: 'state' },
  { code: 'br-rs', name: 'Rio Grande do Sul', type: 'state' },
  { code: 'br-sc', name: 'Santa Catarina', type: 'state' },
  { code: 'br-se', name: 'Sergipe', type: 'state' },
  { code: 'br-sp', name: 'São Paulo', type: 'state' },
  { code: 'br-to', name: 'Tocantins', type: 'state' },
];
