export const PERGUNTAS: Record<number, { p: string; r: string; o: string[] }[]> = {
  1: [ // Português
    { p: "Qual é o plural de 'cidadão'?", r: "Cidadãos", o: ["Cidadões", "Cidadães", "Cidadãos", "Cidadão"] },
    { p: "O que é um verbo?", r: "Ação, estado ou fenômeno", o: ["Nome de algo", "Qualidade", "Ação, estado ou fenômeno", "Lugar"] },
    { p: "Qual palavra é uma oxítona?", r: "Café", o: ["Árvore", "Lápis", "Café", "Mesa"] },
    { p: "Qual é o antônimo de 'alegria'?", r: "Tristeza", o: ["Felicidade", "Tristeza", "Raiva", "Medo"] },
    { p: "Como se escreve corretamente?", r: "Exceção", o: ["Exceção", "Excessão", "Eceção", "Esceção"] },
    { p: "Qual é o sinônimo de 'rápido'?", r: "Veloz", o: ["Lento", "Devagar", "Veloz", "Calmo"] },
    { p: "O que é um adjetivo?", r: "Dá qualidade ao substantivo", o: ["Indica ação", "Dá qualidade ao substantivo", "Substitui o nome", "Liga palavras"] },
    { p: "Qual palavra tem um ditongo?", r: "Pai", o: ["Pai", "Saúde", "Dia", "Lua"] },
    { p: "Qual é o feminino de 'cavaleiro'?", r: "Amazona", o: ["Cavaleira", "Dama", "Amazona", "Égua"] },
    { p: "Qual o coletivo de lobos?", r: "Alcateia", o: ["Manada", "Alcateia", "Matilha", "Bando"] },
    { p: "Qual é o plural de 'pão'?", r: "Pães", o: ["Pãos", "Pães", "Pões", "Pãozes"] },
    { p: "O que é um substantivo?", r: "Dá nome aos seres", o: ["Indica ação", "Dá qualidade", "Dá nome aos seres", "Liga frases"] },
    { p: "Qual palavra é proparoxítona?", r: "Árvore", o: ["Café", "Mesa", "Árvore", "Papel"] },
    { p: "Qual é o antônimo de 'bom'?", r: "Mau", o: ["Ruim", "Mal", "Mau", "Péssimo"] },
    { p: "Como se escreve corretamente?", r: "Pássaro", o: ["Pásaro", "Pássaro", "Passáro", "Páçaro"] }
  ],
  2: [ // Matemática
    { p: "Quanto é 7 x 8?", r: "56", o: ["54", "56", "58", "62"] },
    { p: "Qual é a raiz quadrada de 81?", r: "9", o: ["7", "8", "9", "10"] },
    { p: "Quanto é 150 dividido por 3?", r: "50", o: ["30", "40", "50", "60"] },
    { p: "Qual é o valor de Pi (aproximado)?", r: "3,14", o: ["3,14", "3,16", "3,12", "3,18"] },
    { p: "Quantos graus tem um ângulo reto?", r: "90º", o: ["45º", "90º", "180º", "360º"] },
    { p: "Quanto é 25% de 200?", r: "50", o: ["25", "50", "75", "100"] },
    { p: "Se x + 5 = 12, qual o valor de x?", r: "7", o: ["5", "6", "7", "8"] },
    { p: "Quantos lados tem um hexágono?", r: "6", o: ["5", "6", "7", "8"] },
    { p: "Quanto é 10 ao quadrado?", r: "100", o: ["20", "50", "100", "1000"] },
    { p: "Qual é o dobro de 48?", r: "96", o: ["86", "96", "106", "116"] },
    { p: "Quanto é 9 x 9?", r: "81", o: ["72", "81", "90", "99"] },
    { p: "Qual é a metade de 250?", r: "125", o: ["100", "125", "150", "175"] },
    { p: "Quanto é 1000 - 345?", r: "655", o: ["555", "655", "755", "855"] },
    { p: "Quantos minutos tem 2 horas?", r: "120", o: ["60", "90", "120", "150"] },
    { p: "Qual é o triplo de 15?", r: "45", o: ["30", "45", "60", "75"] }
  ],
  3: [ // Geografia
    { p: "Qual é o maior país do mundo?", r: "Rússia", o: ["Canadá", "China", "Estados Unidos", "Rússia"] },
    { p: "Qual é a capital do Brasil?", r: "Brasília", o: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"] },
    { p: "Em qual continente fica o Egito?", r: "África", o: ["Ásia", "África", "Europa", "América"] },
    { p: "Qual é o maior oceano?", r: "Pacífico", o: ["Atlântico", "Índico", "Pacífico", "Ártico"] },
    { p: "Qual país tem o formato de uma bota?", r: "Itália", o: ["Espanha", "Itália", "Grécia", "França"] },
    { p: "Qual é o rio mais longo do mundo?", r: "Rio Amazonas", o: ["Rio Nilo", "Rio Amazonas", "Rio Mississippi", "Rio Yangtzé"] },
    { p: "Onde fica a Estátua da Liberdade?", r: "Nova York", o: ["Washington", "Los Angeles", "Nova York", "Chicago"] },
    { p: "Qual é o menor país do mundo?", r: "Vaticano", o: ["Mônaco", "Vaticano", "San Marino", "Liechtenstein"] },
    { p: "Qual linha imaginária divide a Terra ao meio?", r: "Linha do Equador", o: ["Trópico de Câncer", "Trópico de Capricórnio", "Linha do Equador", "Meridiano de Greenwich"] },
    { p: "Qual é a capital da Argentina?", r: "Buenos Aires", o: ["Santiago", "Montevidéu", "Buenos Aires", "Lima"] },
    { p: "Qual é o maior estado do Brasil em área?", r: "Amazonas", o: ["Mato Grosso", "Minas Gerais", "Amazonas", "Pará"] },
    { p: "Qual país é conhecido como a terra do sol nascente?", r: "Japão", o: ["China", "Japão", "Coreia do Sul", "Tailândia"] },
    { p: "Qual é o continente mais frio?", r: "Antártida", o: ["Europa", "América do Norte", "Ásia", "Antártida"] },
    { p: "Qual é a capital da França?", r: "Paris", o: ["Londres", "Roma", "Paris", "Madri"] },
    { p: "Onde fica o deserto do Saara?", r: "África", o: ["Ásia", "América do Sul", "África", "Oceania"] }
  ],
  4: [ // História
    { p: "Quem descobriu o Brasil?", r: "Pedro Álvares Cabral", o: ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Dom Pedro I"] },
    { p: "Em que ano o Brasil foi descoberto?", r: "1500", o: ["1492", "1500", "1822", "1889"] },
    { p: "Quem foi o primeiro presidente do Brasil?", r: "Deodoro da Fonseca", o: ["Getúlio Vargas", "Dom Pedro II", "Deodoro da Fonseca", "Juscelino Kubitschek"] },
    { p: "Qual país presenteou os EUA com a Estátua da Liberdade?", r: "França", o: ["Inglaterra", "França", "Espanha", "Alemanha"] },
    { p: "Quem pintou a Mona Lisa?", r: "Leonardo da Vinci", o: ["Michelangelo", "Van Gogh", "Leonardo da Vinci", "Picasso"] },
    { p: "Em que ano começou a Segunda Guerra Mundial?", r: "1939", o: ["1914", "1939", "1945", "1929"] },
    { p: "Quem libertou os escravos no Brasil?", r: "Princesa Isabel", o: ["Dom Pedro I", "Princesa Isabel", "Zumbi dos Palmares", "Tiradentes"] },
    { p: "Qual civilização construiu as pirâmides?", r: "Egípcia", o: ["Maia", "Inca", "Egípcia", "Asteca"] },
    { p: "Quem foi o líder sul-africano que lutou contra o Apartheid?", r: "Nelson Mandela", o: ["Martin Luther King", "Nelson Mandela", "Malcolm X", "Mahatma Gandhi"] },
    { p: "Onde aconteceu a Revolução Industrial?", r: "Inglaterra", o: ["França", "Alemanha", "Inglaterra", "Estados Unidos"] },
    { p: "Quem gritou 'Independência ou Morte'?", r: "Dom Pedro I", o: ["Tiradentes", "Dom Pedro II", "Dom Pedro I", "Deodoro da Fonseca"] },
    { p: "Qual foi a primeira capital do Brasil?", r: "Salvador", o: ["Rio de Janeiro", "Brasília", "Salvador", "São Paulo"] },
    { p: "Quem inventou a lâmpada?", r: "Thomas Edison", o: ["Albert Einstein", "Nikola Tesla", "Thomas Edison", "Alexander Graham Bell"] },
    { p: "Em que ano o homem pisou na Lua?", r: "1969", o: ["1959", "1969", "1979", "1989"] },
    { p: "Qual império foi governado por Júlio César?", r: "Império Romano", o: ["Império Grego", "Império Persa", "Império Romano", "Império Otomano"] }
  ],
  5: [ // Ciências
    { p: "Qual é o planeta mais próximo do Sol?", r: "Mercúrio", o: ["Vênus", "Terra", "Marte", "Mercúrio"] },
    { p: "Qual é o maior órgão do corpo humano?", r: "Pele", o: ["Fígado", "Coração", "Cérebro", "Pele"] },
    { p: "O que as plantas absorvem para fazer fotossíntese?", r: "Gás Carbônico", o: ["Oxigênio", "Gás Carbônico", "Nitrogênio", "Hidrogênio"] },
    { p: "Quantos ossos tem um corpo humano adulto?", r: "206", o: ["196", "206", "216", "226"] },
    { p: "Qual é o estado físico do gelo?", r: "Sólido", o: ["Líquido", "Sólido", "Gasoso", "Plasma"] },
    { p: "Qual animal é conhecido como o rei da selva?", r: "Leão", o: ["Tigre", "Elefante", "Leão", "Gorila"] },
    { p: "Qual é o centro do nosso sistema solar?", r: "Sol", o: ["Terra", "Lua", "Sol", "Júpiter"] },
    { p: "Qual é a fórmula química da água?", r: "H2O", o: ["CO2", "O2", "H2O", "NaCl"] },
    { p: "O que os mamíferos bebem quando nascem?", r: "Leite", o: ["Água", "Suco", "Leite", "Chá"] },
    { p: "Qual força nos mantém no chão?", r: "Gravidade", o: ["Magnetismo", "Atrito", "Gravidade", "Eletricidade"] },
    { p: "Qual é o satélite natural da Terra?", r: "Lua", o: ["Sol", "Marte", "Lua", "Júpiter"] },
    { p: "O que o coração bombeia pelo corpo?", r: "Sangue", o: ["Água", "Ar", "Sangue", "Suco gástrico"] },
    { p: "Qual animal produz mel?", r: "Abelha", o: ["Formiga", "Borboleta", "Abelha", "Mosca"] },
    { p: "Qual é o maior mamífero do mundo?", r: "Baleia Azul", o: ["Elefante", "Girafa", "Baleia Azul", "Rinoceronte"] },
    { p: "Qual parte da planta absorve água da terra?", r: "Raiz", o: ["Folha", "Caule", "Raiz", "Flor"] }
  ],
  6: [ // Entretenimento
    { p: "Qual é o nome do boneco de madeira que queria ser menino?", r: "Pinóquio", o: ["Peter Pan", "Pinóquio", "Gepeto", "Woody"] },
    { p: "Quem é o melhor amigo do Bob Esponja?", r: "Patrick", o: ["Lula Molusco", "Seu Siriguejo", "Sandy", "Patrick"] },
    { p: "Qual super-herói é picado por uma aranha?", r: "Homem-Aranha", o: ["Batman", "Superman", "Homem-Aranha", "Flash"] },
    { p: "Em qual jogo você constrói coisas com blocos?", r: "Minecraft", o: ["Roblox", "Minecraft", "Fortnite", "Free Fire"] },
    { p: "Qual princesa perdeu o sapatinho de cristal?", r: "Cinderela", o: ["Branca de Neve", "Ariel", "Cinderela", "Bela"] },
    { p: "Qual é o nome do vilão de Harry Potter?", r: "Voldemort", o: ["Snape", "Malfoy", "Voldemort", "Grindelwald"] },
    { p: "Qual animal é o Mickey?", r: "Rato", o: ["Cachorro", "Gato", "Pato", "Rato"] },
    { p: "Qual filme tem os personagens Elsa e Anna?", r: "Frozen", o: ["Enrolados", "Moana", "Frozen", "Valente"] },
    { p: "Quem mora em uma lâmpada mágica?", r: "Gênio", o: ["Aladdin", "Jasmine", "Gênio", "Jafar"] },
    { p: "Qual é a cor do Sonic?", r: "Azul", o: ["Vermelho", "Verde", "Amarelo", "Azul"] },
    { p: "Qual é o nome do encanador de macacão vermelho dos videogames?", r: "Mario", o: ["Luigi", "Sonic", "Mario", "Link"] },
    { p: "Qual filme tem brinquedos que ganham vida?", r: "Toy Story", o: ["Carros", "Procurando Nemo", "Toy Story", "Monstros S.A."] },
    { p: "Quem é o herói de Gotham City?", r: "Batman", o: ["Superman", "Flash", "Batman", "Aquaman"] },
    { p: "Qual é o nome do leãozinho em 'O Rei Leão'?", r: "Simba", o: ["Mufasa", "Scar", "Simba", "Timão"] },
    { p: "O que o Popeye come para ficar forte?", r: "Espinafre", o: ["Cenoura", "Espinafre", "Brócolis", "Feijão"] }
  ],
  7: [ // Educação Física
    { p: "Quantos jogadores tem um time de futebol em campo?", r: "11", o: ["9", "10", "11", "12"] },
    { p: "Em qual esporte se usa uma cesta?", r: "Basquete", o: ["Vôlei", "Basquete", "Tênis", "Handebol"] },
    { p: "Qual esporte é praticado na água?", r: "Natação", o: ["Atletismo", "Ginástica", "Natação", "Judô"] },
    { p: "Qual país ganhou mais Copas do Mundo?", r: "Brasil", o: ["Alemanha", "Itália", "Argentina", "Brasil"] },
    { p: "Qual esporte usa uma raquete e uma peteca?", r: "Badminton", o: ["Tênis", "Ping-pong", "Badminton", "Squash"] },
    { p: "O que significa a sigla 'CBF'?", r: "Confederação Brasileira de Futebol", o: ["Clube Brasileiro de Futebol", "Confederação Brasileira de Futebol", "Centro Brasileiro de Futebol", "Comitê Brasileiro de Futebol"] },
    { p: "Qual arte marcial é originária do Brasil?", r: "Capoeira", o: ["Judô", "Karatê", "Capoeira", "Taekwondo"] },
    { p: "No vôlei, quantos toques um time pode dar na bola?", r: "3", o: ["2", "3", "4", "5"] },
    { p: "Qual é a cor da faixa mais alta no Judô?", r: "Preta", o: ["Marrom", "Vermelha", "Preta", "Coral"] },
    { p: "Qual esporte é conhecido como o 'esporte bretão'?", r: "Futebol", o: ["Rugby", "Críquete", "Futebol", "Golfe"] },
    { p: "Qual esporte usa uma bola oval?", r: "Futebol Americano", o: ["Futebol", "Basquete", "Futebol Americano", "Vôlei"] },
    { p: "Onde são realizadas as Olimpíadas?", r: "Em cidades diferentes", o: ["Sempre na Grécia", "Sempre no Brasil", "Em cidades diferentes", "Sempre nos EUA"] },
    { p: "No tênis, o que se usa para bater na bola?", r: "Raquete", o: ["Taco", "Mão", "Raquete", "Pé"] },
    { p: "Qual esporte é praticado com patins no gelo?", r: "Hóquei no gelo", o: ["Esqui", "Snowboard", "Hóquei no gelo", "Curling"] },
    { p: "Qual é o objetivo do golfe?", r: "Acertar a bola no buraco", o: ["Fazer gols", "Derrubar pinos", "Acertar a bola no buraco", "Passar a rede"] }
  ],
  8: [ // Artes
    { p: "Quais são as cores primárias?", r: "Vermelho, Amarelo e Azul", o: ["Verde, Laranja e Roxo", "Vermelho, Amarelo e Azul", "Preto, Branco e Cinza", "Rosa, Marrom e Ciano"] },
    { p: "Quem pintou 'A Noite Estrelada'?", r: "Van Gogh", o: ["Picasso", "Da Vinci", "Van Gogh", "Monet"] },
    { p: "O que é uma escultura?", r: "Arte em 3 dimensões", o: ["Uma pintura", "Um desenho", "Arte em 3 dimensões", "Uma música"] },
    { p: "Qual instrumento tem teclas pretas e brancas?", r: "Piano", o: ["Violão", "Flauta", "Bateria", "Piano"] },
    { p: "Qual artista brasileiro pintou o 'Abaporu'?", r: "Tarsila do Amaral", o: ["Romero Britto", "Tarsila do Amaral", "Cândido Portinari", "Di Cavalcanti"] },
    { p: "O que é origami?", r: "Dobra de papel", o: ["Pintura em tela", "Dobra de papel", "Escultura em argila", "Dança japonesa"] },
    { p: "Qual é a arte de tirar fotos?", r: "Fotografia", o: ["Cinema", "Pintura", "Fotografia", "Teatro"] },
    { p: "Qual cor resulta da mistura de azul e amarelo?", r: "Verde", o: ["Roxo", "Laranja", "Verde", "Marrom"] },
    { p: "O que é um autorretrato?", r: "Pintar a si mesmo", o: ["Pintar uma paisagem", "Pintar um animal", "Pintar a si mesmo", "Pintar um amigo"] },
    { p: "Qual é a arte de atuar em um palco?", r: "Teatro", o: ["Música", "Dança", "Teatro", "Pintura"] },
    { p: "Qual instrumento tem cordas e é tocado com um arco?", r: "Violino", o: ["Piano", "Bateria", "Violino", "Flauta"] },
    { p: "O que é uma natureza-morta?", r: "Pintura de objetos inanimados", o: ["Pintura de animais", "Pintura de pessoas", "Pintura de objetos inanimados", "Pintura de paisagens"] },
    { p: "Qual cor resulta da mistura de vermelho e amarelo?", r: "Laranja", o: ["Verde", "Roxo", "Laranja", "Marrom"] },
    { p: "Quem pintou o teto da Capela Sistina?", r: "Michelangelo", o: ["Da Vinci", "Donatello", "Michelangelo", "Raphael"] },
    { p: "O que é um mosaico?", r: "Arte feita com pequenos pedaços", o: ["Pintura a óleo", "Arte feita com pequenos pedaços", "Escultura de gelo", "Desenho a carvão"] }
  ],
  9: [ // Inglês
    { p: "O que significa 'Dog'?", r: "Cachorro", o: ["Gato", "Cachorro", "Pássaro", "Peixe"] },
    { p: "Como se diz 'Maçã' em inglês?", r: "Apple", o: ["Banana", "Orange", "Apple", "Grape"] },
    { p: "O que significa 'Good morning'?", r: "Bom dia", o: ["Boa tarde", "Boa noite", "Bom dia", "Tchau"] },
    { p: "Como se diz 'Vermelho' em inglês?", r: "Red", o: ["Blue", "Green", "Red", "Yellow"] },
    { p: "O que significa 'Water'?", r: "Água", o: ["Fogo", "Terra", "Água", "Ar"] },
    { p: "Como se diz 'Obrigado' em inglês?", r: "Thank you", o: ["Please", "Sorry", "Thank you", "Hello"] },
    { p: "O que significa 'Book'?", r: "Livro", o: ["Caderno", "Lápis", "Livro", "Borracha"] },
    { p: "Como se diz 'Gato' em inglês?", r: "Cat", o: ["Dog", "Cat", "Bird", "Mouse"] },
    { p: "O que significa 'House'?", r: "Casa", o: ["Carro", "Casa", "Escola", "Rua"] },
    { p: "Como se diz 'Um' em inglês?", r: "One", o: ["Two", "Three", "One", "Four"] },
    { p: "O que significa 'Sun'?", r: "Sol", o: ["Lua", "Estrela", "Sol", "Céu"] },
    { p: "Como se diz 'Menino' em inglês?", r: "Boy", o: ["Girl", "Man", "Boy", "Woman"] },
    { p: "O que significa 'School'?", r: "Escola", o: ["Casa", "Parque", "Escola", "Hospital"] },
    { p: "Como se diz 'Amarelo' em inglês?", r: "Yellow", o: ["Red", "Blue", "Yellow", "Green"] },
    { p: "O que significa 'Friend'?", r: "Amigo", o: ["Inimigo", "Irmão", "Amigo", "Pai"] }
  ],
  10: [ // Francês
    { p: "O que significa 'Bonjour'?", r: "Bom dia", o: ["Boa noite", "Bom dia", "Tchau", "Obrigado"] },
    { p: "Como se diz 'Obrigado' em francês?", r: "Merci", o: ["S'il vous plaît", "Pardon", "Merci", "Oui"] },
    { p: "O que significa 'Oui'?", r: "Sim", o: ["Não", "Talvez", "Sim", "Nunca"] },
    { p: "Como se diz 'Gato' em francês?", r: "Chat", o: ["Chien", "Chat", "Oiseau", "Poisson"] },
    { p: "O que significa 'Pomme'?", r: "Maçã", o: ["Banana", "Laranja", "Maçã", "Uva"] },
    { p: "Como se diz 'Amigo' em francês?", r: "Ami", o: ["Frère", "Père", "Ami", "Mère"] },
    { p: "O que significa 'Eau'?", r: "Água", o: ["Fogo", "Terra", "Água", "Ar"] },
    { p: "Como se diz 'Vermelho' em francês?", r: "Rouge", o: ["Bleu", "Vert", "Rouge", "Jaune"] },
    { p: "O que significa 'Maison'?", r: "Casa", o: ["Carro", "Casa", "Escola", "Rua"] },
    { p: "Como se diz 'Um' em francês?", r: "Un", o: ["Deux", "Trois", "Un", "Quatre"] },
    { p: "O que significa 'Soleil'?", r: "Sol", o: ["Lua", "Estrela", "Sol", "Céu"] },
    { p: "Como se diz 'Cachorro' em francês?", r: "Chien", o: ["Chat", "Chien", "Oiseau", "Cheval"] },
    { p: "O que significa 'École'?", r: "Escola", o: ["Casa", "Parque", "Escola", "Hospital"] },
    { p: "Como se diz 'Amarelo' em francês?", r: "Jaune", o: ["Rouge", "Bleu", "Jaune", "Vert"] },
    { p: "O que significa 'Livre'?", r: "Livro", o: ["Caderno", "Lápis", "Livro", "Borracha"] }
  ]
};
